# Ensemble Classifer Model

## It consist of Logistic regression, K-NN, Decison Tree, Support Vector Machine and Artifical Neural Network(ANN). 


In [433]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob 
import os
import sys
import seaborn as sns
%matplotlib inline
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score

In [434]:
os.chdir('C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab1\\07-08')

In [435]:
os.getcwd()

'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab1\\07-08'

In [436]:
# Importing the DataSet
CDCDataset = pd.read_csv('07_08Final.csv')
CLANN = CDCDataset

In [437]:
CLANN.shape

(10149, 3753)

In [438]:
# if more than 10% of the values are missing then we drop, because data is to sparse
s = CLANN.isnull().apply(sum, axis=0) # count the number of nan in each column
print(s) 

for col in CLANN: 
    if s[col] >= 0.10*10149:  
        del CLANN[col]
   
print(CLANN.shape)

Unnamed: 0        0
SEQN              0
AUXRR101       9010
AUXRR102       9010
AUXRR103       9010
AUXRR104       9010
AUXRR105       9010
AUXRR106       9010
AUXRR107       9010
AUXRR108       9010
AUXRR109       9010
AUXRR110       9010
AUXRR111       9010
AUXRR112       9010
AUXRR113       9010
AUXRR114       9010
AUXRR115       9010
AUXRR116       9010
AUXRR117       9010
AUXRR118       9010
AUXRR119       9010
AUXRR120       9010
AUXRR121       9010
AUXRR122       9010
AUXRR123       9010
AUXRR124       9010
AUXRR125       9010
AUXRR126       9010
AUXRR127       9010
AUXRR128       9010
              ...  
WHQ270         7566
WHQ280A       10068
WHQ280B       10109
WHQ280C       10099
WHQ280D       10064
WHQ280E       10128
WHQ090         6228
WHD100A        9910
WHD100B       10010
WHD100C        9953
WHD100D        9892
WHD100E       10093
WHD100F       10130
WHD100G       10141
WHD100J       10143
WHD100L       10145
WHD100M       10023
WHD100N       10143
WHD100O       10054


In [439]:
CLANN.shape

(10149, 166)

In [440]:
print(CLANN)

       Unnamed: 0   SEQN  BMDSTATS  BMXWT  BMXARML  BMXARMC  PEASCST1  \
0               0  41475       3.0  138.9     37.6     45.2       1.0   
1               1  41476       1.0   22.0     25.1     17.1       1.0   
2               2  41477       1.0   83.9     38.2     34.1       1.0   
3               3  41478       1.0   11.5     14.2     17.3       1.0   
4               4  41479       1.0   65.7     34.1     33.2       1.0   
5               5  41480       1.0   27.0     25.8     20.9       1.0   
6               6  41481       1.0   77.9     43.0     31.0       1.0   
7               7  41482       1.0  101.6     40.0     32.8       1.0   
8               8  41483       3.0  133.1     38.9     40.5       1.0   
9               9  41484       1.0    9.3     14.5     15.2       1.0   
10             10  41485       1.0   64.8     32.6     30.7       1.0   
11             11  41486       1.0   86.2     36.0     35.3       1.0   
12             12  41487       1.0   67.1     37.0 

In [441]:
CLANN.tail()

Unnamed: 0   SEQN  BMDSTATS  BMXWT  BMXARML  BMXARMC  PEASCST1  \
10144       10144  51619       1.0   89.4     39.5     33.9       1.0   
10145       10145  51620       1.0   72.2     35.7     29.3       1.0   
10146       10146  51621       1.0   42.8     33.2     22.2       1.0   
10147       10147  51622       1.0   79.1     38.0     37.5       1.0   
10148       10148  51623       1.0   85.2     38.3     33.3       1.0   

       PEASCTM1  BPXPULS    WTDRD1_x_x   ...    MCQ053  MCQ140  PAAQUEX  \
10144     552.0      1.0   3492.609773   ...       2.0     2.0      1.0   
10145     445.0      1.0  49188.089972   ...       1.0     1.0      1.0   
10146     563.0      1.0   5593.553537   ...       2.0     2.0      1.0   
10147     612.0      1.0  17844.521898   ...       2.0     1.0      1.0   
10148     754.0      1.0  24704.093165   ...       2.0     2.0      1.0   

       RDQ070  RDQ140  AGQ030  RXDUSE        RXDDRUG   RXDDRGID  SMD410  
10144     2.0     1.0     1.0     1.0  b'BENAZEPRIL'  b'd00730'     2.0  
10145     1.0     2.0     2.0     2.0            b''        b''     2.0  
10146     2.0     2.0     2.0     2.0            b''        b''     2.0  
10147     2.0     2.0     2.0     2.0            b''        b''     2.0  
10148     2.0     2.0     2.0     1.0   b'ENALAPRIL'  b'd00013'     2.0  

[5 rows x 166 columns]

In [442]:
CLANN = CLANN.drop(['RXDDRUG','RXDDRGID'], axis=1)

In [443]:
CLANN.shape

(10149, 164)

In [444]:
# Dropping the missing value
CLANN = CLANN.dropna(axis=0, how='any')

In [519]:
CLANN.shape

(6327, 164)

In [520]:
CLANN.isnull().sum()

Unnamed: 0    0
SEQN          0
BMDSTATS      0
BMXWT         0
BMXARML       0
BMXARMC       0
PEASCST1      0
PEASCTM1      0
BPXPULS       0
WTDRD1_x_x    0
DR1ILINE      0
DR1DRSTZ_x    0
DR1EXMER_x    0
DRABF_x       0
DRDINT_x      0
DR1DBIH_x     0
DR1DAY_x      0
DR1LANG_x     0
DR1CCMNM      0
DR1CCMTX      0
DR1_020       0
DR1_030Z      0
DR1IFDCD      0
DR1MC         0
WTDRD1_y_x    0
DR1DRSTZ_y    0
DR1EXMER_y    0
DRABF_y       0
DRDINT_y      0
DR1DBIH_y     0
             ..
HOQ070        0
HOQ080        0
HSAQUEX       0
HUQ010        0
HUQ020        0
HUQ030        0
HUQ050        0
HUQ071        0
IMQ011        0
IMQ020        0
INQ020        0
INQ012        0
INQ030        0
INQ060        0
INQ080        0
INQ090        0
INQ132        0
INQ140        0
INQ150        0
IND235        0
INDFMMPC      0
MCQ010        0
MCQ053        0
MCQ140        0
PAAQUEX       0
RDQ070        0
RDQ140        0
AGQ030        0
RXDUSE        0
SMD410        0
Length: 164, dtype: int6

In [521]:
# Don't to Don't know
CLANN= CLANN.replace(999999,9)

In [522]:
# Don't to Don't know
CLANN= CLANN.replace(999,9)

In [523]:
# refused to Don't know
CLANN= CLANN.replace(777,9)

In [524]:
# don't know to No
CLANN= CLANN.replace(9,2)

In [525]:
# Borderline to yes
CLANN= CLANN.replace(3,1)

In [526]:
CLANN.shape

(6327, 164)

In [527]:
#CLANN = pd.read_csv('datasetclann.csv')

In [528]:
#CLANN = CLANN.to_csv("datasetclann.csv")

In [529]:
# Locking the data set and selecting the X(Independent) and Y (Dependent) Variable 
X = CLANN.iloc[:, 1:164]
y= CLANN.loc[:,['DIQ010']]

In [530]:
print(X)

        SEQN  BMDSTATS  BMXWT  BMXARML  BMXARMC  PEASCST1  PEASCTM1  BPXPULS  \
0      41475       1.0  138.9     37.6     45.2       1.0     612.0      1.0   
1      41476       1.0   22.0     25.1     17.1       1.0       2.0      1.0   
2      41477       1.0   83.9     38.2     34.1       1.0     625.0      1.0   
4      41479       1.0   65.7     34.1     33.2       1.0     620.0      1.0   
5      41480       1.0   27.0     25.8     20.9       1.0      79.0      1.0   
6      41481       1.0   77.9     43.0     31.0       1.0     533.0      1.0   
7      41482       1.0  101.6     40.0     32.8       1.0     561.0      1.0   
8      41483       1.0  133.1     38.9     40.5       1.0     748.0      1.0   
10     41485       1.0   64.8     32.6     30.7       1.0     547.0      1.0   
11     41486       1.0   86.2     36.0     35.3       1.0     556.0      1.0   
12     41487       1.0   67.1     37.0     29.9       1.0     539.0      1.0   
13     41488       1.0   16.1     22.0  

In [531]:
# Scaling the feature in standard form.
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)

#Normalizing the dataset
#from sklearn import preprocessing
#X = preprocessing.normalize(X)
#y = preprocessing.normalize(y)

In [532]:
# Splitting the dataset into training and test

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=0)

In [533]:
X_train.shape,

((4428, 163),)

In [534]:
X_test.shape

(1899, 163)

In [535]:
print(X)

[[-1.71656382  0.          2.42854858 ...  0.38587744 -1.11696111
   0.48925777]
 [-1.7162246   0.         -1.49223674 ...  0.38587744 -1.11696111
   0.48925777]
 [-1.71588539  0.          0.58386772 ...  0.38587744 -1.11696111
   0.48925777]
 ...
 [ 1.72440145  0.          0.7683358  ... -2.59149641 -1.11696111
   0.48925777]
 [ 1.72474066  0.          0.19145379 ...  0.38587744  0.89528631
   0.48925777]
 [ 1.7257583   0.          0.62746927 ...  0.38587744 -1.11696111
   0.48925777]]


# Logistic Regression Model

In [536]:
#Fitting Logistic Regression trainning data
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE
regressor = LogisticRegression()
rfe = RFE(regressor, 15)
rfe = rfe.fit(X_train,y_train.values.ravel())
#X_train, X_test, y_train, y_test = train_test_split(rfe,y,test_size=0.30,random_state=0)
#rfe = RFE(regressor,20 )
#rfe = rfe.fit(X, Y )
print(rfe.support_)
print(rfe.ranking_)

[False False False False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False  True
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False False False False False False False  True  True
 False False False False False False False False False False False False
 False False  True False False False False False False False False False
 False False False False False False False  True  True False False False
 False  True False False False False False False  True False False  True
  True False False False False False False False False False False False
 False False False  True  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False  True False]
[ 24 14

In [537]:
print(rfe.ranking_)

[ 24 149   2   3   1 141 106 100  61  78 148 108 140  66 107 136  81  86
  65  28  18  39 134  76 144  72 145 114 120 139  43  25 112  64  87   1
 126  21  69 128  34  20  84 124 143 110   1 142 101  90 137  91  48 123
  88 133  79 129  32 119 105   7  11  70  46 146 147  33  23   6   1   1
  47  55  71  27 117  41  13  74  38  15  93  12  68  35   1 102  80 103
 116  17  44  45 131 135  22  16  42  95 122  73  40   1   1  96 132 118
 138   1  75  67  60 130 125  56   1  82 109   1   1  97  51  98  99  52
 115  62  31  54 113  57  14  85 121   1   1  19  26 127  10  63 111  37
  83  36   4  89   9   8  59  58  49  94  30  77 104  53   5  50  29   1
  92]


In [538]:
# Need to select only the true variables
print(rfe)

RFE(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
  n_features_to_select=15, step=1, verbose=0)


In [539]:
# Locking the data set and selecting the X(Independent) and Y (Dependent) Variable 
X= CLANN.loc[:,['BMXARMC','DRQSDIET','RIDAGEMN','CBD070','CBD090','CBD150','DBD910','HSAQUEX','HUQ010','RXDUSE']]
y= CLANN.loc[:,['DIQ010']]

# Splitting the dataset into training and test

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=0)

In [540]:
# fit model with new selected variable
regressor = LogisticRegression(random_state = 22)
regressor.fit(X_train,y_train.values.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=22, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [541]:
# Predicting the Training data set accuracy
y_pred = regressor.predict(X_test)

In [542]:
from sklearn.metrics import accuracy_score
print('Test Accuracy score:' , accuracy_score(y_test, y_pred))

Test Accuracy score: 0.9125855713533438


In [543]:
target_names = ['Yes', 'No']
print(classification_report(y_test, y_pred, target_names=target_names))

             precision    recall  f1-score   support

        Yes       0.00      0.00      0.00       163
         No       0.91      1.00      0.95      1736

avg / total       0.84      0.91      0.87      1899



In [544]:
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.metrics import roc_curve, auc
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(false_positive_rate, true_positive_rate)
roc_auc

ValueError: Data is not binary and pos_label is not specified

#  K-Nearest Neighbors classifier

In [489]:
# Importing the KNN model classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=25)

In [490]:
# Fitting the Model
knn = knn.fit(X_train, y_train.values.ravel())

In [491]:
#Prediction
y_pred = knn.predict(X_test)

In [492]:
from sklearn.metrics import accuracy_score
print('Accuracy score:' , accuracy_score(y_test, y_pred))

Accuracy score: 0.9141653501843076


In [493]:
target_names = ['Yes', 'No']
print(classification_report(y_test, y_pred, target_names=target_names))

             precision    recall  f1-score   support

        Yes       0.00      0.00      0.00       163
         No       0.91      1.00      0.96      1736

avg / total       0.84      0.91      0.87      1899



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Support Vector Machine Model

In [494]:
# Importing the SVM model classifier
from sklearn.svm import SVC
Model_svc = SVC(gamma='auto')

In [495]:
# Fitting the Model
Model_svc.fit(X_train, y_train.values.ravel())

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [496]:
#Prediction
y_pred = Model_svc.predict(X_test)

In [497]:
from sklearn.metrics import accuracy_score
print('Accuracy score:' , accuracy_score(y_test, y_pred))

Accuracy score: 0.9141653501843076


In [498]:
target_names = ['Yes', 'No']
print(classification_report(y_test, y_pred, target_names=target_names))

             precision    recall  f1-score   support

        Yes       0.00      0.00      0.00       163
         No       0.91      1.00      0.96      1736

avg / total       0.84      0.91      0.87      1899



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## Cross Validation using k-fold (10 fold cross validation) 

In [499]:
# Cross Validation (Training dataset)

from sklearn.model_selection import cross_val_score

scores = cross_val_score(Model_svc,X_train,y_train.values.ravel(),cv=10)

scores

array([0.90990991, 0.90990991, 0.91196388, 0.91196388, 0.91196388,
       0.91196388, 0.91176471, 0.91176471, 0.91176471, 0.91176471])

In [500]:
# Cross Validation (Test dataset)
scores = cross_val_score(Model_svc,X_test,y_test.values.ravel(),cv=10)

scores

array([0.91099476, 0.91099476, 0.91099476, 0.91578947, 0.91578947,
       0.91578947, 0.91534392, 0.91534392, 0.91534392, 0.91534392])

In [501]:
from sklearn.metrics import accuracy_score
print('Accuracy score: %0.3f (+/- %0.3f)'%  (scores.mean(), scores.std()*2 ))

Accuracy score: 0.914 (+/- 0.004)


In [502]:
from sklearn.metrics import accuracy_score
print('Accuracy score:' , accuracy_score(y_test, y_pred))

Accuracy score: 0.9141653501843076


# Decision Tree Classifcation model

In [503]:
# Imprting the Model and instantiating it into clf i.e. short name for classification
from sklearn import tree
clf_DT = tree.DecisionTreeClassifier()

In [504]:
clf_DT = clf_DT.fit(X_train, y_train)

In [505]:
y_pred = clf_DT.predict(X_test)

In [506]:
from sklearn.metrics import accuracy_score
print('Accuracy score:' , accuracy_score(y_test,y_pred))
#print("Test set score: %f" % clf.score(y_test, y_pred))

Accuracy score: 0.8794102159031069


In [507]:
target_names = ['Yes', 'No']
print(classification_report(y_test, y_pred, target_names=target_names))

             precision    recall  f1-score   support

        Yes       0.28      0.26      0.27       163
         No       0.93      0.94      0.93      1736

avg / total       0.88      0.88      0.88      1899



## Cross Validation using k-fold (10 fold cross validation)

In [508]:
# Cross Validation Training dataset

from sklearn.model_selection import cross_val_score

scores = cross_val_score(clf_DT,X_train,y_train.values.ravel(),cv=10)

scores

array([0.88063063, 0.86036036, 0.86907449, 0.8510158 , 0.86004515,
       0.86455982, 0.86425339, 0.86877828, 0.85972851, 0.87782805])

In [509]:
# Cross Validation (Test dataset)
scores = cross_val_score(clf_DT,X_test,y_test.values.ravel(),cv=10)

scores

array([0.86387435, 0.86910995, 0.86387435, 0.9       , 0.88421053,
       0.84736842, 0.85185185, 0.88888889, 0.84126984, 0.86243386])

In [510]:
from sklearn.metrics import accuracy_score
print('Accuracy score: %0.3f (+/- %0.3f)'%  (scores.mean(), scores.std()*2 ))

Accuracy score: 0.867 (+/- 0.036)


#  Neural Network Model

In [511]:
from sklearn.neural_network import MLPClassifier
from sklearn.feature_selection import RFE
X = (X_train)
y = (y_train)
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
     hidden_layer_sizes=(5,2),random_state=1)
rfe = RFE(clf, 10)
rfe = rfe.fit(X_train,y_train.values.ravel())
#X_train, X_test, y_train, y_test = train_test_split(rfe,y,test_size=0.30,random_state=0)
#rfe = RFE(regressor,20 )
#rfe = rfe.fit(X, Y )
print(rfe.support_)
print(rfe.ranking_)

[ True  True  True  True  True  True  True  True  True  True]
[1 1 1 1 1 1 1 1 1 1]


In [512]:
from sklearn.neural_network import MLPClassifier
X = (X_train)
y = (y_train)
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
     hidden_layer_sizes=(5,2),random_state=1)

clf.fit(X, y.values.ravel())  

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [513]:
clf.predict(X_test)

array([2., 2., 2., ..., 2., 2., 2.])

In [114]:
#print("Training set score: %f" % clf.score(X_train, y_train))
#print("Test set score: %f" % clf.score(X_test, y_test))

In [514]:
from sklearn.metrics import accuracy_score
print('Accuracy score:' , accuracy_score(y_test,y_pred))

Accuracy score: 0.8794102159031069


In [515]:
target_names = ['Yes', 'No']
print(classification_report(y_test, y_pred, target_names=target_names))

             precision    recall  f1-score   support

        Yes       0.28      0.26      0.27       163
         No       0.93      0.94      0.93      1736

avg / total       0.88      0.88      0.88      1899



In [516]:
# Average Ensemble for Classification for CLANN

import pandas
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier


X = X_train
Y = y_train.values.ravel()
seed = 22
kfold = model_selection.KFold(n_splits=10, random_state=seed)
# create the sub models
estimators = []
model1 = LogisticRegression()
estimators.append(('logistic', model1))
model2 = DecisionTreeClassifier()
estimators.append(('cart', model2))
model3 = SVC()
estimators.append(('svm', model3))
model4 = KNeighborsClassifier()
estimators.append(('knn', model4))
# create the ensemble model
ensemble = VotingClassifier(estimators)
results = model_selection.cross_val_score(ensemble, X, Y, cv=kfold)
print(results.mean())

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but i

0.9076294904139812


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [517]:
# Average Ensemble for Classification for CLANN

import pandas
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score

X = X_test
Y = y_test
seed = 22
kfold = model_selection.KFold(n_splits=10, random_state=seed)
# create the sub models
estimators = []
model1 = LogisticRegression()

estimators.append(('logistic', model1))
model2 = DecisionTreeClassifier()
estimators.append(('cart', model2))
model3 = SVC()
estimators.append(('svm', model3))
model4 = KNeighborsClassifier()
estimators.append(('knn', model4))
# create the ensemble model
ensemble = VotingClassifier(estimators)
results = model_selection.cross_val_score(ensemble, X, Y, cv=kfold)
print(results.mean())

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y

0.9141631857421331


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [518]:
target_names = ['Yes', 'No']
print(classification_report(y_test, y_pred, target_names=target_names))

             precision    recall  f1-score   support

        Yes       0.28      0.26      0.27       163
         No       0.93      0.94      0.93      1736

avg / total       0.88      0.88      0.88      1899



In [151]:
# ROC curve for the learning representation of all models -

from sklearn.metrics import roc_curve

def plot_roc_curve(ytest, regressor, knn, model_svc, clf_DT):
    """Plot the roc curve for base learners and ensemble."""
    plt.figure(figsize=(10, 8))
    plt.plot([0, 1], [0, 1], 'k--')
    
    cm = [plt.cm.rainbow(i)
      for i in np.linspace(0, 1.0, regressor.shape[1] + 1)]
    
    for i in range(regressor.shape[1]):
        p = regressor[:, i]
        fpr, tpr, _ = roc_curve(ytest, p)
        plt.plot(fpr, tpr, knn=knn[i], c=cm[i + 1])

    fpr, tpr, _ = roc_curve(ytest, model_svc)
    plt.plot(fpr, tpr, label=clf_DT, c=cm[0])
        
    plt.xlabel('False positive rate')
    plt.ylabel('True positive rate')
    plt.title('ROC curve')
    plt.legend(frameon=False)
    plt.show()


plot_roc_curve(y_test, P.values, P.mean(axis=1), list(P.columns), "ensemble")

NameError: name 'P' is not defined