## We Imported the dataset in form of CSV file. Below we are going to implement the feature selection. We will be applying two feature selection method. 1) Variance Threshold. 2) Univariate Feature selection under which we will be using kBest method.

### Variance Threshold will remove all the feature falling under under the decided threshold i.e. in our case .6 and provide only those having meet the threshold level.

### kBest method will remove all the feature except the freature having kBest scoring meet.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob 
import os
import sys
import seaborn as sns
%matplotlib inline
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
os.getcwd()

'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab1\\CDCDiab_1.0\\CDCDiab_1.0'

In [3]:
os.chdir('C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab1\\07-08')

In [4]:
# Importing the DataSet
CDCDataset = pd.read_csv('07_08Final.csv')
DFreg = CDCDataset

In [5]:
DFreg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10149 entries, 0 to 10148
Columns: 3753 entries, Unnamed: 0 to WHQ150
dtypes: float64(3738), int64(2), object(13)
memory usage: 290.6+ MB


In [9]:
# Dropping Missing Value 

DF_Final = DFreg.dropna(axis=0,how=all,thresh=20) 

In [10]:
DF_Final.shape

(10149, 3753)

In [12]:
# Locking the data set and selecting the X(Independent) and Y (Dependent) Variable 
X= DF_Final.iloc[:,0:3752]
y= DF_Final.loc[:,['DIQ010']]

In [13]:
# Splitting the dataset into training and test

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=22)

In [14]:
# Dumy Encoding through One hot Encoder

import numpy as np
def to_one_hot(labels, dimension=10):
results = np.zeros((len(labels), dimension))
for i, label in enumerate(labels):
results[i, label] = 1.
return results

one_hot_train_labels = to_one_hot(train_labels)
one_hot_test_labels = to_one_hot(test_labels)

IndentationError: expected an indented block (<ipython-input-14-1bba553ac57f>, line 5)

In [34]:
#DFreg= DFreg.loc[:,['SEQN','DIQ010','BPQ020','BPQ030','BPQ035','BPQ040','BPQ080']] 
DFreg= DFreg.loc[:,['SEQN','DIQ010','BPQ020','BPQ057','BPQ080']] 

In [35]:
DFreg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10149 entries, 0 to 10148
Data columns (total 5 columns):
SEQN      10149 non-null int64
DIQ010    9666 non-null float64
BPQ020    6546 non-null float64
BPQ057    6209 non-null float64
BPQ080    4218 non-null float64
dtypes: float64(4), int64(1)
memory usage: 396.5 KB


In [36]:
# Droping the missing NAN values
DFreg=DFreg.dropna()

In [37]:
DFreg.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3919 entries, 0 to 10148
Data columns (total 5 columns):
SEQN      3919 non-null int64
DIQ010    3919 non-null float64
BPQ020    3919 non-null float64
BPQ057    3919 non-null float64
BPQ080    3919 non-null float64
dtypes: float64(4), int64(1)
memory usage: 183.7 KB


In [38]:
X= DFreg.loc[:,['BPQ020','BPQ057','BPQ080']]
y= DFreg.loc[:,['DIQ010']]

In [39]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3919 entries, 0 to 10148
Data columns (total 3 columns):
BPQ020    3919 non-null float64
BPQ057    3919 non-null float64
BPQ080    3919 non-null float64
dtypes: float64(3)
memory usage: 122.5 KB


In [40]:
y.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3919 entries, 0 to 10148
Data columns (total 1 columns):
DIQ010    3919 non-null float64
dtypes: float64(1)
memory usage: 61.2 KB


In [41]:
from sklearn.feature_selection import VarianceThreshold
Feature_sel = VarianceThreshold(threshold=(.6 * (1-.6)))
Feature_sel.fit(X)
Feature_sel.transform(X)

array([[1., 1., 2.],
       [1., 2., 1.],
       [1., 9., 2.],
       ...,
       [1., 2., 2.],
       [1., 1., 1.],
       [2., 2., 1.]])

In [42]:
Feature_sel.transform(X).shape

(3919, 3)

In [43]:
print(Feature_sel.transform(X))

[[1. 1. 2.]
 [1. 2. 1.]
 [1. 9. 2.]
 ...
 [1. 2. 2.]
 [1. 1. 1.]
 [2. 2. 1.]]


In [44]:
print(Feature_sel)

VarianceThreshold(threshold=0.24)


## Univariate Feature Selection
### kBest method

In [45]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

# For getting details about SelectKbest method-
#SelectKBest?

sel = SelectKBest(chi2, k=2)
sel.fit(X,y)

SelectKBest(k=2, score_func=<function chi2 at 0x0000021304855A60>)

In [46]:
sel.transform(X).shape

(3919, 2)

In [49]:
sel.transform(X)

array([[1., 2.],
       [1., 1.],
       [1., 2.],
       ...,
       [1., 2.],
       [1., 1.],
       [2., 1.]])

In [50]:
sel.transform(X).shape

(3919, 2)

In [47]:
sel.scores_

array([32.86163143,  1.80966662, 17.08720471])