In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob 
import os
import sys
import seaborn as sns
%matplotlib inline
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score

In [3]:
os.chdir('C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab1\\07-08')

In [4]:
# Importing the DataSet
CDCDataset = pd.read_csv('07_08Final.csv')
DF_Final = CDCDataset

In [5]:
DF_Done =  DF_Final.loc[:,['ALQ101','BPQ052','PAQ620','RIAGENDR','RIDAGEYR','RIDRETH1','DMDEDUC2','INDHHIN2','DIQ010']]

In [6]:
DF_Done.shape

(10149, 9)

In [7]:
DF_Done.describe()

ALQ101       BPQ052       PAQ620      RIAGENDR      RIDAGEYR  \
count  5233.000000  6546.000000  7105.000000  10149.000000  1.014900e+04   
mean      1.306707     2.021387     1.628571      1.497882  3.296719e+01   
std       0.526212     0.748312     0.491310      0.500020  2.548364e+01   
min       1.000000     1.000000     1.000000      1.000000  5.397605e-79   
25%       1.000000     2.000000     1.000000      1.000000  9.000000e+00   
50%       1.000000     2.000000     2.000000      1.000000  2.900000e+01   
75%       2.000000     2.000000     2.000000      2.000000  5.500000e+01   
max       9.000000     9.000000     9.000000      2.000000  8.000000e+01   

           RIDRETH1     DMDEDUC2      INDHHIN2       DIQ010  
count  10149.000000  5935.000000  10072.000000  9666.000000  
mean       2.766085     3.180455     10.377085     1.937099  
std        1.146737     1.312210     14.544560     0.364736  
min        1.000000     1.000000      1.000000     1.000000  
25%        2.000000     2.000000      5.000000     2.000000  
50%        3.000000     3.000000      7.000000     2.000000  
75%        4.000000     4.000000     12.000000     2.000000  
max        5.000000     9.000000     99.000000     9.000000

In [8]:
DF_model = DF_Done.dropna(axis=0, how='any')

In [9]:
# Locking the data set and selecting the X(Independent) and Y (Dependent) Variable 
X= DF_model.loc[:,['ALQ101','BPQ052','PAQ620','RIAGENDR','RIDAGEYR','RIDRETH1','DMDEDUC2','INDHHIN2']]
y= DF_model.loc[:,['DIQ010']]

In [10]:
DF_model.to_csv('replicate.csv')

In [11]:
X.shape

(5207, 8)

In [12]:
y.shape

(5207, 1)

In [13]:
# Splitting the dataset into training and test
# Suprising results had been found that is we decrease the test ratio to 0.25 then the reults accuracy is drop by 1.12% in ensemble average.

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=22)

In [14]:
'''from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)'''

'from sklearn.preprocessing import StandardScaler\nsc_X = StandardScaler()\nX_train = sc_X.fit_transform(X_train)\nX_test = sc_X.transform(X_test)\nsc_y = StandardScaler()\ny_train = sc_y.fit_transform(y_train)'

In [15]:
# Feature Selection 

'''from sklearn.feature_selection import VarianceThreshold
Feature_sel = VarianceThreshold(threshold=(.6 * (1-.6)))
Feature_sel.fit(X)
Feature_sel.transform(X)'''

'from sklearn.feature_selection import VarianceThreshold\nFeature_sel = VarianceThreshold(threshold=(.6 * (1-.6)))\nFeature_sel.fit(X)\nFeature_sel.transform(X)'

In [17]:
# Fitting Logistic Regression trainning data

from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression(random_state = 22)
regressor.fit(X_train,y_train.values.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=22, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [18]:
# Predicting the Training data set accuracy
y_pred = regressor.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score
print('Accuracy score:' , accuracy_score(y_test, y_pred))

Accuracy score: 0.8413307741522713


In [20]:
# Confusion matrix output
from sklearn.metrics import  confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[   1  212    0    0]
 [   2 1314    0    0]
 [   1   31    0    0]
 [   0    2    0    0]]


#  SVM

In [21]:
# Importing the SVM model classifier
from sklearn import svm
Model_svm = svm.SVC()

In [22]:
# Fitting the Model
Model_svm.fit(X_train, y_train.values.ravel())

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [23]:
#Prediction
y_pred = Model_svm.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score
print('Accuracy score:' , accuracy_score(y_test, y_pred))

Accuracy score: 0.8419705694177864


In [27]:
from sklearn.metrics import classification_report

target_names = ['class 1', 'class 2']
print(classification_report(y_test, y_pred, target_names=target_names))

             precision    recall  f1-score   support

    class 1       0.00      0.00      0.00       213
    class 2       0.84      1.00      0.91      1316

avg / total       0.71      0.84      0.77      1563



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1428: UserWarning: labels size, 4, does not match size of target_names, 2
  .format(len(labels), len(target_names))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Ensemble Model -

## This paper only uses the Logistic regression model but going a step further we tried to implement some other classification model and check the training and test accuracy.

## Training Accuracy-  

In [97]:
# Average Ensemble for Classification for CLANN

X = X_train
Y = y_train
seed = 22
kfold = model_selection.KFold(n_splits=10, random_state=22)
# create the sub models
estimators = []
model1 = LogisticRegression()
estimators.append(('logistic', model1))
model2 = DecisionTreeClassifier()
estimators.append(('cart', model2))
model3 = SVC()
estimators.append(('svm', model3))
# create the ensemble model
ensemble = VotingClassifier(estimators)
results = model_selection.cross_val_score(ensemble, X, Y, cv=kfold)
print('Training Results Accuracy Ensemble mean:', results.mean())

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y

Training Results Accuracy Ensemble mean - 0.8608640674394101


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


## Test Accuracy

In [98]:
# Average Ensemble for Classification for CLANN

X = X_test
Y = y_test
seed = 22
kfold = model_selection.KFold(n_splits=10, random_state=22)
# create the sub models
estimators = []
model1 = LogisticRegression()
estimators.append(('logistic', model1))
model2 = DecisionTreeClassifier()
estimators.append(('cart', model2))
model3 = SVC()
estimators.append(('svm', model3))
# create the ensemble model
ensemble = VotingClassifier(estimators)
results = model_selection.cross_val_score(ensemble, X, Y, cv=kfold)
print('Test Results Accuracy Ensemble mean :', results.mean())

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y

Test Results Accuracy Ensemble mean - 0.8368732647395067


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
