In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob 
import os
import sys
import seaborn as sns
%matplotlib inline
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [4]:
os.chdir('C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab1\\07-08')

In [5]:
# Importing the DataSet
CDCDataset = pd.read_csv('07_08Final.csv')
DF_Final = CDCDataset

In [6]:
DF_Done =  DF_Final.loc[:,['ALQ101','BPQ052','PAQ620','RIAGENDR','RIDAGEYR','RIDRETH1','DMDEDUC2','INDHHIN2','DIQ010']]

In [7]:
DF_Done.shape

(10149, 9)

In [8]:
DF_Done.describe()

ALQ101       BPQ052       PAQ620      RIAGENDR      RIDAGEYR  \
count  5233.000000  6546.000000  7105.000000  10149.000000  1.014900e+04   
mean      1.306707     2.021387     1.628571      1.497882  3.296719e+01   
std       0.526212     0.748312     0.491310      0.500020  2.548364e+01   
min       1.000000     1.000000     1.000000      1.000000  5.397605e-79   
25%       1.000000     2.000000     1.000000      1.000000  9.000000e+00   
50%       1.000000     2.000000     2.000000      1.000000  2.900000e+01   
75%       2.000000     2.000000     2.000000      2.000000  5.500000e+01   
max       9.000000     9.000000     9.000000      2.000000  8.000000e+01   

           RIDRETH1     DMDEDUC2      INDHHIN2       DIQ010  
count  10149.000000  5935.000000  10072.000000  9666.000000  
mean       2.766085     3.180455     10.377085     1.937099  
std        1.146737     1.312210     14.544560     0.364736  
min        1.000000     1.000000      1.000000     1.000000  
25%        2.000000     2.000000      5.000000     2.000000  
50%        3.000000     3.000000      7.000000     2.000000  
75%        4.000000     4.000000     12.000000     2.000000  
max        5.000000     9.000000     99.000000     9.000000

In [31]:
DF_model = DF_Done.dropna(axis=0, how='any')

In [32]:
# Locking the data set and selecting the X(Independent) and Y (Dependent) Variable 
X= DF_model.loc[:,['ALQ101','BPQ052','PAQ620','RIAGENDR','RIDAGEYR','RIDRETH1','DMDEDUC2','INDHHIN2']]
y= DF_model.loc[:,['DIQ010']]

In [33]:
X.shape

(5207, 8)

In [34]:
y.shape

(5207, 1)

In [38]:
# Splitting the dataset into training and test

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=22)

In [36]:
'''from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)'''

In [ ]:
# Feature Selection 

'''from sklearn.feature_selection import VarianceThreshold
Feature_sel = VarianceThreshold(threshold=(.6 * (1-.6)))
Feature_sel.fit(X)
Feature_sel.transform(X)'''

In [39]:
# Fitting Logistic Regression trainning data

from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression(random_state = 22)
regressor.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=22, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [40]:
# Predicting the Training data set accuracy
y_pred = regressor.predict(X_test)

In [41]:
from sklearn.metrics import accuracy_score
print('Accuracy score:' , accuracy_score(y_test, y_pred))

Accuracy score: 0.8413307741522713


In [42]:
# Confusion matrix output
from sklearn.metrics import  confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[   1  212    0    0]
 [   2 1314    0    0]
 [   1   31    0    0]
 [   0    2    0    0]]


#  SVM

In [43]:
# Importing the SVM model classifier
from sklearn import svm
Model_svm = svm.SVC()

In [44]:
# Fitting the Model
Model_svm.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [45]:
#Prediction
y_pred = Model_svm.predict(X_test)

In [46]:
from sklearn.metrics import accuracy_score
print('Accuracy score:' , accuracy_score(y_test, y_pred))

Accuracy score: 0.8419705694177864
